Visualize cell state
glitchcore/last_cell pull request #2
Opened 2020-04-21 19:21 UTC by not-fl3

Place some colored primitives depending on the cell's calc_count

I have no idea what I am doing actually, but looks kinda cool!

2020-04-21 19:45 UTC, glitchcore requested changes

2020-04-21 19:45 UTC, glitchcore commented on sphere_playground.gd
> +func choose_visual(visuals, active):
Все-таки select, а не choose

2020-04-21 19:45 UTC, glitchcore commented on Main.gd
> +			cells_state[x][y].visuals = sphere_playground.create_visuals(x, y)
Меня смущает, что есть отдельно geometry и draw_cell, а есть visuals. Я думаю, все можно привести к одной логике

2020-04-21 19:45 UTC, glitchcore commented on Main.gd
> +			if need_update:
почему бы не вызывать choose_visual из draw_cell, чтобы не дублировать логику + сохранить ее внутри модуля sphere_playground

2020-04-21 20:01 UTC, not-fl3 commented on sphere_playground.gd
> +func choose_visual(visuals, active):
Надо узнать есть ли в годоте методы, было бы круто сделать местный `fn select(&self, ..)`

2020-04-24 08:39 UTC, glitchcore commented on sphere_playground.gd
> +func choose_visual(visuals, active):
Так это уже метод. Каждый файл — это класс и все функции — методы, self передается неявно, все «глобальные» переменные на самом деле — члены класса.

2020-04-24 08:48 UTC, glitchcore commented
В общем, предлагаю сделать так:
1. Добавить в init_cell поля "cube_mass", "pyramid_mass"
2. Смержить оба пути отрисовки объектов
3. Выбирать максимальную величину из "sphere_mass", "cube_mass", "pyramid_mass" и рисовать соответствующий объект.
4. Для сферы менять радиус, для пирамиды — x/z scale менять ×1, y scale менять ×2, чтобы она вытягивалась вверх. Для куба менять только высоту.

2023-06-22 07:45 UTC, closed without merging